### ISSUE TITLE
👀 

### ISSUE THREAD

**Issue by Sansossio** [mate-rs/mate#1]
https://github.com/mate-rs/mate/blob/8dbbe00bb164693d00bd551775141cae1c2fd99c/src/bin/main.rs#L11

**Comment by EstebanBorai** [comment]
Hey @Sansossio! Thanks so much for checking out. Im still drafting on this repo!

I have fixed the hardcoded string to use `REDIS_URL` instead, you can check it out here: https://github.com/mate-rs/mate/commit/a1af0fceb2604d9a589bdc960246e8cf9737ec30
